<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
             $permissions = [
            ['id' => 1, 'name' => 'Can add permission', 'content_type_id' => 1, 'codename' => 'add_permission'],
            ['id' => 2, 'name' => 'Can change permission', 'content_type_id' => 1, 'codename' => 'change_permission'],
            ['id' => 3, 'name' => 'Can delete permission', 'content_type_id' => 1, 'codename' => 'delete_permission'],
            ['id' => 4, 'name' => 'Can view permission', 'content_type_id' => 1, 'codename' => 'view_permission'],
            ['id' => 5, 'name' => 'Can add group', 'content_type_id' => 2, 'codename' => 'add_group'],
            ['id' => 6, 'name' => 'Can change group', 'content_type_id' => 2, 'codename' => 'change_group'],
            ['id' => 7, 'name' => 'Can delete group', 'content_type_id' => 2, 'codename' => 'delete_group'],
            ['id' => 8, 'name' => 'Can view group', 'content_type_id' => 2, 'codename' => 'view_group'],
            ['id' => 9, 'name' => 'Can add content type', 'content_type_id' => 3, 'codename' => 'add_contenttype'],
            ['id' => 10, 'name' => 'Can change content type', 'content_type_id' => 3, 'codename' => 'change_contenttype'],
            ['id' => 11, 'name' => 'Can delete content type', 'content_type_id' => 3, 'codename' => 'delete_contenttype'],
            ['id' => 12, 'name' => 'Can view content type', 'content_type_id' => 3, 'codename' => 'view_contenttype'],
            ['id' => 13, 'name' => 'Can add session', 'content_type_id' => 4, 'codename' => 'add_session'],
            ['id' => 14, 'name' => 'Can change session', 'content_type_id' => 4, 'codename' => 'change_session'],
            ['id' => 15, 'name' => 'Can delete session', 'content_type_id' => 4, 'codename' => 'delete_session'],
            ['id' => 16, 'name' => 'Can view session', 'content_type_id' => 4, 'codename' => 'view_session'],
            ['id' => 17, 'name' => 'Can add site', 'content_type_id' => 5, 'codename' => 'add_site'],
            ['id' => 18, 'name' => 'Can change site', 'content_type_id' => 5, 'codename' => 'change_site'],
            ['id' => 19, 'name' => 'Can delete site', 'content_type_id' => 5, 'codename' => 'delete_site'],
            ['id' => 20, 'name' => 'Can view site', 'content_type_id' => 5, 'codename' => 'view_site'],
            ['id' => 21, 'name' => 'Can add log entry', 'content_type_id' => 6, 'codename' => 'add_logentry'],
            ['id' => 22, 'name' => 'Can change log entry', 'content_type_id' => 6, 'codename' => 'change_logentry'],
            ['id' => 23, 'name' => 'Can delete log entry', 'content_type_id' => 6, 'codename' => 'delete_logentry'],
            ['id' => 24, 'name' => 'Can view log entry', 'content_type_id' => 6, 'codename' => 'view_logentry'],
            ['id' => 25, 'name' => 'Can add email address', 'content_type_id' => 7, 'codename' => 'add_emailaddress'],
            ['id' => 26, 'name' => 'Can change email address', 'content_type_id' => 7, 'codename' => 'change_emailaddress'],
            ['id' => 27, 'name' => 'Can delete email address', 'content_type_id' => 7, 'codename' => 'delete_emailaddress'],
            ['id' => 28, 'name' => 'Can view email address', 'content_type_id' => 7, 'codename' => 'view_emailaddress'],
            ['id' => 29, 'name' => 'Can add email confirmation', 'content_type_id' => 8, 'codename' => 'add_emailconfirmation'],
            ['id' => 30, 'name' => 'Can change email confirmation', 'content_type_id' => 8, 'codename' => 'change_emailconfirmation'],
            ['id' => 31, 'name' => 'Can delete email confirmation', 'content_type_id' => 8, 'codename' => 'delete_emailconfirmation'],
            ['id' => 32, 'name' => 'Can view email confirmation', 'content_type_id' => 8, 'codename' => 'view_emailconfirmation'],
            ['id' => 33, 'name' => 'Can add social account', 'content_type_id' => 9, 'codename' => 'add_socialaccount'],
            ['id' => 34, 'name' => 'Can change social account', 'content_type_id' => 9, 'codename' => 'change_socialaccount'],
            ['id' => 35, 'name' => 'Can delete social account', 'content_type_id' => 9, 'codename' => 'delete_socialaccount'],
            ['id' => 36, 'name' => 'Can view social account', 'content_type_id' => 9, 'codename' => 'view_socialaccount'],
            ['id' => 37, 'name' => 'Can add social application', 'content_type_id' => 10, 'codename' => 'add_socialapp'],
            ['id' => 38, 'name' => 'Can change social application', 'content_type_id' => 10, 'codename' => 'change_socialapp'],
            ['id' => 39, 'name' => 'Can delete social application', 'content_type_id' => 10, 'codename' => 'delete_socialapp'],
            ['id' => 40, 'name' => 'Can view social application', 'content_type_id' => 10, 'codename' => 'view_socialapp'],
            ['id' => 41, 'name' => 'Can add social application token', 'content_type_id' => 11, 'codename' => 'add_socialtoken'],
            ['id' => 42, 'name' => 'Can change social application token', 'content_type_id' => 11, 'codename' => 'change_socialtoken'],
            ['id' => 43, 'name' => 'Can delete social application token', 'content_type_id' => 11, 'codename' => 'delete_socialtoken'],
            ['id' => 44, 'name' => 'Can view social application token', 'content_type_id' => 11, 'codename' => 'view_socialtoken'],
            ['id' => 45, 'name' => 'Can add user', 'content_type_id' => 12, 'codename' => 'add_user'],
            ['id' => 46, 'name' => 'Can change user', 'content_type_id' => 12, 'codename' => 'change_user'],
            ['id' => 47, 'name' => 'Can delete user', 'content_type_id' => 12, 'codename' => 'delete_user'],
            ['id' => 48, 'name' => 'Can view user', 'content_type_id' => 12, 'codename' => 'view_user'],
            ['id' => 49, 'name' => 'Can add Entreprise', 'content_type_id' => 13, 'codename' => 'add_entreprise'],
            ['id' => 50, 'name' => 'Can change Entreprise', 'content_type_id' => 13, 'codename' => 'change_entreprise'],
            ['id' => 51, 'name' => 'Can delete Entreprise', 'content_type_id' => 13, 'codename' => 'delete_entreprise'],
            ['id' => 52, 'name' => 'Can view Entreprise', 'content_type_id' => 13, 'codename' => 'view_entreprise'],
            ['id' => 53, 'name' => 'Can add Site', 'content_type_id' => 14, 'codename' => 'add_site'],
            ['id' => 54, 'name' => 'Can change Site', 'content_type_id' => 14, 'codename' => 'change_site'],
            ['id' => 55, 'name' => 'Can delete Site', 'content_type_id' => 14, 'codename' => 'delete_site'],
            ['id' => 56, 'name' => 'Can view Site', 'content_type_id' => 14, 'codename' => 'view_site'],
            ['id' => 57, 'name' => 'Can add Addresse', 'content_type_id' => 15, 'codename' => 'add_addresse'],
            ['id' => 58, 'name' => 'Can change Addresse', 'content_type_id' => 15, 'codename' => 'change_addresse'],
            ['id' => 59, 'name' => 'Can delete Addresse', 'content_type_id' => 15, 'codename' => 'delete_addresse'],
            ['id' => 60, 'name' => 'Can view Addresse', 'content_type_id' => 15, 'codename' => 'view_addresse'],
            ['id' => 61, 'name' => 'Can add annee financiere', 'content_type_id' => 16, 'codename' => 'add_anneefinanciere'],
            ['id' => 62, 'name' => 'Can change annee financiere', 'content_type_id' => 16, 'codename' => 'change_anneefinanciere'],
            ['id' => 63, 'name' => 'Can delete annee financiere', 'content_type_id' => 16, 'codename' => 'delete_anneefinanciere'],
            ['id' => 64, 'name' => 'Can view annee financiere', 'content_type_id' => 16, 'codename' => 'view_anneefinanciere'],
            ['id' => 65, 'name' => 'Peut fermer l\'année financière', 'content_type_id' => 16, 'codename' => 'can_close_annee_financiere'],
            ['id' => 66, 'name' => 'Can add employe', 'content_type_id' => 17, 'codename' => 'add_employe'],
            ['id' => 67, 'name' => 'Can change employe', 'content_type_id' => 17, 'codename' => 'change_employe'],
            ['id' => 68, 'name' => 'Can delete employe', 'content_type_id' => 17, 'codename' => 'delete_employe'],
            ['id' => 69, 'name' => 'Can view employe', 'content_type_id' => 17, 'codename' => 'view_employe'],
            ['id' => 70, 'name' => 'Can add poste', 'content_type_id' => 18, 'codename' => 'add_poste'],
            ['id' => 71, 'name' => 'Can change poste', 'content_type_id' => 18, 'codename' => 'change_poste'],
            ['id' => 72, 'name' => 'Can delete poste', 'content_type_id' => 18, 'codename' => 'delete_poste'],
            ['id' => 73, 'name' => 'Can view poste', 'content_type_id' => 18, 'codename' => 'view_poste'],
            ['id' => 74, 'name' => 'Can add historique poste', 'content_type_id' => 19, 'codename' => 'add_historiqueposte'],
            ['id' => 75, 'name' => 'Can change historique poste', 'content_type_id' => 19, 'codename' => 'change_historiqueposte'],
            ['id' => 76, 'name' => 'Can delete historique poste', 'content_type_id' => 19, 'codename' => 'delete_historiqueposte'],
            ['id' => 77, 'name' => 'Can view historique poste', 'content_type_id' => 19, 'codename' => 'view_historiqueposte'],
            ['id' => 78, 'name' => 'Can add historique gestionnaire', 'content_type_id' => 20, 'codename' => 'add_historiquegestionnaire'],
            ['id' => 79, 'name' => 'Can change historique gestionnaire', 'content_type_id' => 20, 'codename' => 'change_historiquegestionnaire'],
            ['id' => 80, 'name' => 'Can delete historique gestionnaire', 'content_type_id' => 20, 'codename' => 'delete_historiquegestionnaire'],
            ['id' => 81, 'name' => 'Can view historique gestionnaire', 'content_type_id' => 20, 'codename' => 'view_historiquegestionnaire'],
            ['id' => 82, 'name' => 'Can add historique adresse', 'content_type_id' => 21, 'codename' => 'add_historiqueadresse'],
            ['id' => 83, 'name' => 'Can change historique adresse', 'content_type_id' => 21, 'codename' => 'change_historiqueadresse'],
            ['id' => 84, 'name' => 'Can delete historique adresse', 'content_type_id' => 21, 'codename' => 'delete_historiqueadresse'],
            ['id' => 85, 'name' => 'Can view historique adresse', 'content_type_id' => 21, 'codename' => 'view_historiqueadresse'],
            ['id' => 86, 'name' => 'Can add Code de travail', 'content_type_id' => 22, 'codename' => 'add_codedetravail'],
            ['id' => 87, 'name' => 'Can change Code de travail', 'content_type_id' => 22, 'codename' => 'change_codedetravail'],
            ['id' => 88, 'name' => 'Can delete Code de travail', 'content_type_id' => 22, 'codename' => 'delete_codedetravail'],
            ['id' => 89, 'name' => 'Can view Code de travail', 'content_type_id' => 22, 'codename' => 'view_codedetravail'],
            ['id' => 90, 'name' => 'Can add Configuration de code de travail', 'content_type_id' => 23, 'codename' => 'add_configurationcodedetravail'],
            ['id' => 91, 'name' => 'Can change Configuration de code de travail', 'content_type_id' => 23, 'codename' => 'change_configurationcodedetravail'],
            ['id' => 92, 'name' => 'Can delete Configuration de code de travail', 'content_type_id' => 23, 'codename' => 'delete_configurationcodedetravail'],
            ['id' => 93, 'name' => 'Can view Configuration de code de travail', 'content_type_id' => 23, 'codename' => 'view_configurationcodedetravail'],
            ['id' => 94, 'name' => 'Can add feuille de temps', 'content_type_id' => 24, 'codename' => 'add_feuilledetemps'],
            ['id' => 95, 'name' => 'Can change feuille de temps', 'content_type_id' => 24, 'codename' => 'change_feuilledetemps'],
            ['id' => 96, 'name' => 'Can delete feuille de temps', 'content_type_id' => 24, 'codename' => 'delete_feuilledetemps'],
            ['id' => 97, 'name' => 'Can view feuille de temps', 'content_type_id' => 24, 'codename' => 'view_feuilledetemps'],
            ['id' => 98, 'name' => 'Peut activer une feuille de temps', 'content_type_id' => 24, 'codename' => 'can_activate_feuille_de_temps'],
            ['id' => 99, 'name' => 'Peut valider une feuille de temps', 'content_type_id' => 24, 'codename' => 'can_validate_operation'],
            ['id' => 100, 'name' => 'Peut retourner une feuille de temps', 'content_type_id' => 24, 'codename' => 'can_return_operation'],
            ['id' => 101, 'name' => 'Peut désactiver une feuille de temps', 'content_type_id' => 24, 'codename' => 'can_deactivate_feuille_de_temps'],
            ['id' => 102, 'name' => 'Peut définir une semaine de paie', 'content_type_id' => 24, 'codename' => 'can_define_payroll_week'],
            ['id' => 103, 'name' => 'Can add Affectation d\'employé à un code de travail', 'content_type_id' => 25, 'codename' => 'add_employeaffecteaucodedetravail'],
            ['id' => 104, 'name' => 'Can change Affectation d\'employé à un code de travail', 'content_type_id' => 25, 'codename' => 'change_employeaffecteaucodedetravail'],
            ['id' => 105, 'name' => 'Can delete Affectation d\'employé à un code de travail', 'content_type_id' => 25, 'codename' => 'delete_employeaffecteaucodedetravail'],
            ['id' => 106, 'name' => 'Can view Affectation d\'employé à un code de travail', 'content_type_id' => 25, 'codename' => 'view_employeaffecteaucodedetravail'],
            ['id' => 107, 'name' => 'Can add Demande d\'absence', 'content_type_id' => 26, 'codename' => 'add_demandeabsence'],
            ['id' => 108, 'name' => 'Can change Demande d\'absence', 'content_type_id' => 26, 'codename' => 'change_demandeabsence'],
            ['id' => 109, 'name' => 'Can delete Demande d\'absence', 'content_type_id' => 26, 'codename' => 'delete_demandeabsence'],
            ['id' => 110, 'name' => 'Can view Demande d\'absence', 'content_type_id' => 26, 'codename' => 'view_demandeabsence'],
            ['id' => 111, 'name' => 'Peut approuver une demande d\'absence', 'content_type_id' => 26, 'codename' => 'can_approve_absence'],
            ['id' => 112, 'name' => 'Peut rejeter une demande d\'absence', 'content_type_id' => 26, 'codename' => 'can_reject_absence'],
            ['id' => 113, 'name' => 'Can add Opération', 'content_type_id' => 27, 'codename' => 'add_operation'],
            ['id' => 114, 'name' => 'Can change Opération', 'content_type_id' => 27, 'codename' => 'change_operation'],
            ['id' => 115, 'name' => 'Can delete Opération', 'content_type_id' => 27, 'codename' => 'delete_operation'],
            ['id' => 116, 'name' => 'Can view Opération', 'content_type_id' => 27, 'codename' => 'view_operation'],
            ['id' => 117, 'name' => 'Can add ligne de travail', 'content_type_id' => 28, 'codename' => 'add_lignedetravail'],
            ['id' => 118, 'name' => 'Can change ligne de travail', 'content_type_id' => 28, 'codename' => 'change_lignedetravail'],
            ['id' => 119, 'name' => 'Can delete ligne de travail', 'content_type_id' => 28, 'codename' => 'delete_lignedetravail'],
            ['id' => 120, 'name' => 'Can view ligne de travail', 'content_type_id' => 28, 'codename' => 'view_lignedetravail'],
            ['id' => 121, 'name' => 'Can add heure reguliere', 'content_type_id' => 29, 'codename' => 'add_heurereguliere'],
            ['id' => 122, 'name' => 'Can change heure reguliere', 'content_type_id' => 29, 'codename' => 'change_heurereguliere'],
            ['id' => 123, 'name' => 'Can delete heure reguliere', 'content_type_id' => 29, 'codename' => 'delete_heurereguliere'],
            ['id' => 124, 'name' => 'Can view heure reguliere', 'content_type_id' => 29, 'codename' => 'view_heurereguliere'],
            ['id' => 125, 'name' => 'Can add completed task', 'content_type_id' => 30, 'codename' => 'add_completedtask'],
            ['id' => 126, 'name' => 'Can change completed task', 'content_type_id' => 30, 'codename' => 'change_completedtask'],
            ['id' => 127, 'name' => 'Can delete completed task', 'content_type_id' => 30, 'codename' => 'delete_completedtask'],
            ['id' => 128, 'name' => 'Can view completed task', 'content_type_id' => 30, 'codename' => 'view_completedtask'],
            ['id' => 129, 'name' => 'Can add detail completed task', 'content_type_id' => 31, 'codename' => 'add_detailcompletedtask'],
            ['id' => 130, 'name' => 'Can change detail completed task', 'content_type_id' => 31, 'codename' => 'change_detailcompletedtask'],
            ['id' => 131, 'name' => 'Can delete detail completed task', 'content_type_id' => 31, 'codename' => 'delete_detailcompletedtask'],
            ['id' => 132, 'name' => 'Can view detail completed task', 'content_type_id' => 31, 'codename' => 'view_detailcompletedtask'],
        ];

        DB::table('permissions')->insert($permissions);
    }
}
