<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
 $permissionUsers = [
            // User ID 3 permissions
            ['user_id' => 3, 'permission_id' => 61],
            ['user_id' => 3, 'permission_id' => 62],
            ['user_id' => 3, 'permission_id' => 63],
            ['user_id' => 3, 'permission_id' => 64],
            ['user_id' => 3, 'permission_id' => 52],
            ['user_id' => 3, 'permission_id' => 56],
            ['user_id' => 3, 'permission_id' => 66],
            ['user_id' => 3, 'permission_id' => 67],
            ['user_id' => 3, 'permission_id' => 68],
            ['user_id' => 3, 'permission_id' => 69],
            ['user_id' => 3, 'permission_id' => 82],
            ['user_id' => 3, 'permission_id' => 83],
            ['user_id' => 3, 'permission_id' => 84],
            ['user_id' => 3, 'permission_id' => 85],
            ['user_id' => 3, 'permission_id' => 78],
            ['user_id' => 3, 'permission_id' => 79],
            ['user_id' => 3, 'permission_id' => 80],
            ['user_id' => 3, 'permission_id' => 81],
            ['user_id' => 3, 'permission_id' => 74],
            ['user_id' => 3, 'permission_id' => 75],
            ['user_id' => 3, 'permission_id' => 76],
            ['user_id' => 3, 'permission_id' => 77],
            ['user_id' => 3, 'permission_id' => 70],
            ['user_id' => 3, 'permission_id' => 71],
            ['user_id' => 3, 'permission_id' => 72],
            ['user_id' => 3, 'permission_id' => 73],
            ['user_id' => 3, 'permission_id' => 107],
            ['user_id' => 3, 'permission_id' => 108],
            ['user_id' => 3, 'permission_id' => 109],
            ['user_id' => 3, 'permission_id' => 110],
            ['user_id' => 3, 'permission_id' => 121],
            ['user_id' => 3, 'permission_id' => 122],
            ['user_id' => 3, 'permission_id' => 123],
            ['user_id' => 3, 'permission_id' => 124],
            ['user_id' => 3, 'permission_id' => 113],
            ['user_id' => 3, 'permission_id' => 114],
            ['user_id' => 3, 'permission_id' => 115],
            ['user_id' => 3, 'permission_id' => 116],
            ['user_id' => 3, 'permission_id' => 86],
            ['user_id' => 3, 'permission_id' => 87],
            ['user_id' => 3, 'permission_id' => 88],
            ['user_id' => 3, 'permission_id' => 89],
            ['user_id' => 3, 'permission_id' => 90],
            ['user_id' => 3, 'permission_id' => 91],
            ['user_id' => 3, 'permission_id' => 92],
            ['user_id' => 3, 'permission_id' => 93],
            ['user_id' => 3, 'permission_id' => 105],
            ['user_id' => 3, 'permission_id' => 106],
            ['user_id' => 3, 'permission_id' => 94],
            ['user_id' => 3, 'permission_id' => 100],
            ['user_id' => 3, 'permission_id' => 99],
            ['user_id' => 3, 'permission_id' => 95],
            ['user_id' => 3, 'permission_id' => 96],
            ['user_id' => 3, 'permission_id' => 97],
            ['user_id' => 3, 'permission_id' => 20],
            ['user_id' => 3, 'permission_id' => 45],
            ['user_id' => 3, 'permission_id' => 46],
            ['user_id' => 3, 'permission_id' => 47],
            ['user_id' => 3, 'permission_id' => 48],

            // User ID 4 permissions
            ['user_id' => 4, 'permission_id' => 61],
            ['user_id' => 4, 'permission_id' => 62],
            ['user_id' => 4, 'permission_id' => 63],
            ['user_id' => 4, 'permission_id' => 64],
            ['user_id' => 4, 'permission_id' => 52],
            ['user_id' => 4, 'permission_id' => 56],
            ['user_id' => 4, 'permission_id' => 66],
            ['user_id' => 4, 'permission_id' => 67],
            ['user_id' => 4, 'permission_id' => 68],
            ['user_id' => 4, 'permission_id' => 69],
            ['user_id' => 4, 'permission_id' => 82],
            ['user_id' => 4, 'permission_id' => 83],
            ['user_id' => 4, 'permission_id' => 84],
            ['user_id' => 4, 'permission_id' => 85],
            ['user_id' => 4, 'permission_id' => 78],
            ['user_id' => 4, 'permission_id' => 79],
            ['user_id' => 4, 'permission_id' => 80],
            ['user_id' => 4, 'permission_id' => 81],
            ['user_id' => 4, 'permission_id' => 74],
            ['user_id' => 4, 'permission_id' => 75],
            ['user_id' => 4, 'permission_id' => 76],
            ['user_id' => 4, 'permission_id' => 77],
            ['user_id' => 4, 'permission_id' => 70],
            ['user_id' => 4, 'permission_id' => 71],
            ['user_id' => 4, 'permission_id' => 72],
            ['user_id' => 4, 'permission_id' => 73],
            ['user_id' => 4, 'permission_id' => 107],
            ['user_id' => 4, 'permission_id' => 108],
            ['user_id' => 4, 'permission_id' => 109],
            ['user_id' => 4, 'permission_id' => 110],
            ['user_id' => 4, 'permission_id' => 121],
            ['user_id' => 4, 'permission_id' => 122],
            ['user_id' => 4, 'permission_id' => 123],
            ['user_id' => 4, 'permission_id' => 124],
            ['user_id' => 4, 'permission_id' => 113],
            ['user_id' => 4, 'permission_id' => 114],
            ['user_id' => 4, 'permission_id' => 115],
            ['user_id' => 4, 'permission_id' => 116],
            ['user_id' => 4, 'permission_id' => 86],
            ['user_id' => 4, 'permission_id' => 87],
            ['user_id' => 4, 'permission_id' => 88],
            ['user_id' => 4, 'permission_id' => 89],
            ['user_id' => 4, 'permission_id' => 90],
            ['user_id' => 4, 'permission_id' => 91],
            ['user_id' => 4, 'permission_id' => 92],
            ['user_id' => 4, 'permission_id' => 93],
            ['user_id' => 4, 'permission_id' => 105],
            ['user_id' => 4, 'permission_id' => 106],
            ['user_id' => 4, 'permission_id' => 94],
            ['user_id' => 4, 'permission_id' => 100],
            ['user_id' => 4, 'permission_id' => 99],
            ['user_id' => 4, 'permission_id' => 95],
            ['user_id' => 4, 'permission_id' => 96],
            ['user_id' => 4, 'permission_id' => 97],
            ['user_id' => 4, 'permission_id' => 20],
            ['user_id' => 4, 'permission_id' => 45],
            ['user_id' => 4, 'permission_id' => 46],
            ['user_id' => 4, 'permission_id' => 47],
            ['user_id' => 4, 'permission_id' => 48],

            // User ID 5 permissions
            ['user_id' => 5, 'permission_id' => 61],
            ['user_id' => 5, 'permission_id' => 62],
            ['user_id' => 5, 'permission_id' => 63],
            ['user_id' => 5, 'permission_id' => 64],
            ['user_id' => 5, 'permission_id' => 52],
            ['user_id' => 5, 'permission_id' => 56],
            ['user_id' => 5, 'permission_id' => 66],
            ['user_id' => 5, 'permission_id' => 67],
            ['user_id' => 5, 'permission_id' => 68],
            ['user_id' => 5, 'permission_id' => 69],
            ['user_id' => 5, 'permission_id' => 82],
            ['user_id' => 5, 'permission_id' => 83],
            ['user_id' => 5, 'permission_id' => 84],
            ['user_id' => 5, 'permission_id' => 85],
            ['user_id' => 5, 'permission_id' => 78],
            ['user_id' => 5, 'permission_id' => 79],
            ['user_id' => 5, 'permission_id' => 80],
            ['user_id' => 5, 'permission_id' => 81],
            ['user_id' => 5, 'permission_id' => 74],
            ['user_id' => 5, 'permission_id' => 75],
            ['user_id' => 5, 'permission_id' => 76],
            ['user_id' => 5, 'permission_id' => 77],
            ['user_id' => 5, 'permission_id' => 70],
            ['user_id' => 5, 'permission_id' => 71],
            ['user_id' => 5, 'permission_id' => 72],
            ['user_id' => 5, 'permission_id' => 73],
            ['user_id' => 5, 'permission_id' => 107],
            ['user_id' => 5, 'permission_id' => 108],
            ['user_id' => 5, 'permission_id' => 109],
            ['user_id' => 5, 'permission_id' => 110],
            ['user_id' => 5, 'permission_id' => 121],
            ['user_id' => 5, 'permission_id' => 122],
            ['user_id' => 5, 'permission_id' => 123],
            ['user_id' => 5, 'permission_id' => 124],
            ['user_id' => 5, 'permission_id' => 113],
            ['user_id' => 5, 'permission_id' => 114],
            ['user_id' => 5, 'permission_id' => 115],
            ['user_id' => 5, 'permission_id' => 116],
            ['user_id' => 5, 'permission_id' => 86],
            ['user_id' => 5, 'permission_id' => 87],
            ['user_id' => 5, 'permission_id' => 88],
            ['user_id' => 5, 'permission_id' => 89],
            ['user_id' => 5, 'permission_id' => 90],
            ['user_id' => 5, 'permission_id' => 91],
            ['user_id' => 5, 'permission_id' => 92],
            ['user_id' => 5, 'permission_id' => 93],
            ['user_id' => 5, 'permission_id' => 105],
            ['user_id' => 5, 'permission_id' => 106],
            ['user_id' => 5, 'permission_id' => 94],
            ['user_id' => 5, 'permission_id' => 100],
            ['user_id' => 5, 'permission_id' => 99],
            ['user_id' => 5, 'permission_id' => 95],
            ['user_id' => 5, 'permission_id' => 96],
            ['user_id' => 5, 'permission_id' => 97],
            ['user_id' => 5, 'permission_id' => 20],
            ['user_id' => 5, 'permission_id' => 45],
            ['user_id' => 5, 'permission_id' => 46],
            ['user_id' => 5, 'permission_id' => 47],
            ['user_id' => 5, 'permission_id' => 48],

            // User ID 6 permissions
            ['user_id' => 6, 'permission_id' => 69],
            ['user_id' => 6, 'permission_id' => 81],
            ['user_id' => 6, 'permission_id' => 77],
            ['user_id' => 6, 'permission_id' => 73],
            ['user_id' => 6, 'permission_id' => 107],
            ['user_id' => 6, 'permission_id' => 108],
            ['user_id' => 6, 'permission_id' => 109],
            ['user_id' => 6, 'permission_id' => 110],
            ['user_id' => 6, 'permission_id' => 121],
            ['user_id' => 6, 'permission_id' => 122],
            ['user_id' => 6, 'permission_id' => 123],
            ['user_id' => 6, 'permission_id' => 124],
            ['user_id' => 6, 'permission_id' => 113],
            ['user_id' => 6, 'permission_id' => 114],
            ['user_id' => 6, 'permission_id' => 115],
            ['user_id' => 6, 'permission_id' => 116],
            ['user_id' => 6, 'permission_id' => 105],
            ['user_id' => 6, 'permission_id' => 106],
            ['user_id' => 6, 'permission_id' => 100],
            ['user_id' => 6, 'permission_id' => 97],
            ['user_id' => 6, 'permission_id' => 46],
            ['user_id' => 6, 'permission_id' => 48],
        ];

        DB::table('permission_user')->insert($permissionUsers);
    }
}
